apiVersion: v1
kind: PersistentVolume
metadata:
  name: ashu-pv1 # name of pv -- this is outside namespace 
spec: 
  storageClassName: local
  accessModes:
  - ReadWriteOnce # RWM /RWO /ROM 
  capacity:
    storage: 3Gi # requesting 3Gb storage 
  hostPath:
    path: /data/ashuvol1
    type: DirectoryOrCreate #  if not present above directory then create it