apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupodx1
  name: ashupodx1
spec:
  volumes:  # creating volume 
  - name: ashudatavol1  # name of volume
    emptyDir: {}  # type of volume 
  containers:
  - image: alpine 
    name: ashuc1 
    volumeMounts: # mounting volume 
    - name: ashudatavol1
      mountPath: /mnt/data/
    command: ['sh','-c','while true; do date >>/mnt/data/time.txt;sleep 10;done']
  - image: nginx
    name: ashuc2 # name of container 
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts: # to attach volume to container 
    - name: ashudatavol1
      mountPath: /usr/share/nginx/html/
      readOnly: true 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
